import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkLoaded, ClerkProvider } from '@clerk/nextjs'
import Footer from './components/global/Footer'
import Navigation from './components/global/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className} bg-[#FAE8FF]`}><ClerkLoaded><Navigation />{children}<Footer /></ClerkLoaded></body>
    </html>
    </ClerkProvider>
  )
}
